config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resource :sessions, only: :destroy
  resource :users_sessions, only: %i(new create destroy)
  resource :tenants_sessions, only: %i(new create destroy)

  resources :users, only: %i(new create destroy index)
  resources :tenants, only: %i(new create)
end

app/models/tenant.rb
require Rails.root.join('lib', 'validators', 'subdomain_validator')

class Tenant < ActiveRecord::Base
  after_create :create_apartment_tenant
  after_destroy :drop_apartment_tenant

  has_secure_password

  validates_presence_of :email, :name
  validates_uniqueness_of :email

  validates :name, presence: true,
            uniqueness: true,
            subdomain: true

  private

  def create_apartment_tenant
    Apartment::Tenant.create(name)
  end

  def drop_apartment_tenant
    Apartment::Tenant.drop(name)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :email
  validates_uniqueness_of :email

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :check_subdomain

  include WardenHelper
  include UrlHelper

  def check_subdomain
    return if request.subdomain.empty? || request.subdomain == 'public'

    if signed_in? && current_user_type_is_tenant? && request.subdomain != current_user.name
      flash[:danger] = 'You are not authorized to access that subdomain.'
      redirect_to root_url(subdomain: current_user.name)
    end
  end
end

app/controllers/concerns/warden_helper.rb
module WardenHelper
  extend ActiveSupport::Concern

  included do
    helper_method :warden, :signed_in?, :current_user, :current_user_type_is_tenant?

    prepend_before_action :authenticate!
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user
    warden.user
  end

  def current_user_type_is_tenant?
    current_user.is_a? Tenant
  end

  def current_user_type_is_user?
    current_user.is_a? User
  end

  def warden
    request.env['warden']
  end

  def authenticate!
    warden.authenticate!
  end

  def set_user(user)
    warden.set_user(user)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate!

  def index

  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  skip_before_action :authenticate!

  def create
    authenticate!

    redirect_to :root
  end

  def destroy
    warden.logout

    redirect_to :root
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate!
  before_action :logout, except: :new

  def new

  end

  def create
    authenticate!

    redirect_to :root
  end

  def destroy
    Apartment::Tenant.switch!('public')

    redirect_to :root
  end

  private

  def logout
    warden.logout
  end
end

app/controllers/tenants_controller.rb
class TenantsController < ApplicationController
  skip_before_action :authenticate!

  def new
    @tenant = Tenant.new
  end

  def create
    @tenant = Tenant.new(tenant_params)

    if @tenant.save
      flash[:success] = "Tenant #{@tenant.email} was created"

      set_user(@tenant)

      redirect_to root_url(subdomain: @tenant.name)
    else
      flash[:danger] = @tenant.errors.full_messages.join(', ')

      render :new
    end
  end

  private

  def tenant_params
    params.require(:tenant).permit(:password, :password_confirmation, :name, :email)
  end
end

app/controllers/tenants_sessions_controller.rb
class TenantsSessionsController < SessionsController
  skip_before_action :check_subdomain, only: :create

  def create
    authenticate!

    redirect_to root_url(subdomain: current_user.name)
  end
end

app/controllers/unauthorized_controller.rb
class UnauthorizedController < ActionController::Metal
  include ActionController::UrlFor
  include ActionController::Redirecting
  include Rails.application.routes.url_helpers
  include Rails.application.routes.mounted_helpers

  delegate :flash, to: :request

  def self.call(env)
    @respond ||= action(:respond)
    @respond.call(env)
  end

  def respond
    unless request.get?
      message = env['warden.options'].fetch(:message, "unauthorized.user")

      flash[:danger] = I18n.t(message)
    end

    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :current_user_tenant?
  before_action :set_schema

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = "#{@user.email} was created"

      redirect_to root_path
    else
      flash[:danger] = @user.errors.full_messages.join(',')

      render :new
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy

    flash[:success] = "#{@user.email} was deleted"
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

  def current_user_tenant?
    render status: 403, text: 'Not authorized' unless current_user_type_is_tenant?
  end

  def set_schema
    return unless current_user_type_is_tenant?

    Apartment::Tenant.switch!(current_user.name)
  end
end

app/controllers/users_sessions_controller.rb
class UsersSessionsController < SessionsController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/url_helper.rb
module UrlHelper
  def with_subdomain(subdomain)
    subdomain = (subdomain || '')
    subdomain += '.' unless subdomain.empty?
    [subdomain, request.domain, request.port_string].join
  end

  def url_for(options = nil)
    if options.kind_of?(Hash) && options.has_key?(:subdomain)
      options[:host] = with_subdomain(options.delete(:subdomain))
    end
    super
  end
end

app/views/home/index.html.haml
%h1 Welcome

- if signed_in?
  %h2= "#{current_user.class.name} login for #{current_user.email} success"

  - if current_user_type_is_tenant?
    = link_to 'All Users', users_path

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-default{role: :banner}
  .container
    .collapse.navbar-collapse{role: :navigation}
      %ul.nav.navbar-nav.navbar-right
        - unless signed_in?
          %li= link_to 'User login', new_users_sessions_path

        %li.divider-vertical

        - if signed_in?
          %li= link_to "Sign out (#{current_user.email})", sessions_path, method: :delete
        - else
          %li= link_to 'Tenant login', new_tenants_sessions_path
          %li= link_to 'Tenant register', new_tenant_path

app/views/layouts/_messages.html.haml
- flash.each do |key, value|
  %div{class: "alert alert-#{key}", role: 'alert'}= value

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    = stylesheet_link_tag 'application', media: 'all'
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    .container
      = render 'layouts/messages'
      = yield
    = javascript_include_tag 'application'

app/views/tenants/new.html.haml
= form_for @tenant do |f|
  .form-group
    = f.label :email
    = f.email_field :email, class: 'form-control'

  .form-group
    = f.label :password
    = f.password_field :password, class: 'form-control'

  .form-group
    = f.label :password_confirmation
    = f.password_field :password_confirmation, class: 'form-control'

  .form-group
    = f.label :name, 'Subdomain name'
    = f.text_field :name, class: 'form-control', data: {subdomain_validation: true}

    .subdomain-errors.field_with_errors

  = f.submit 'Create', class: 'btn btn-primary'

app/views/tenants_sessions/new.html.haml
%h1 Sign in
.row
  .col-md-6.col-md-offset-3
    = form_for(:tenant, url: tenants_sessions_path, html: {id: 'session'}) do |f|

      .form-group
        = f.label :email
        = f.email_field :email, class: 'form-control'

      .form-group
        = f.label :password
        = f.password_field :password, class: 'form-control'

      = f.submit 'Sign in', class: 'btn btn-primary'

app/views/users/_user.html.haml
%tr
  %td= user.email
  %td
    = link_to t('.delete'), user_path(user), data: { confirm: 'Are you sure' },
                method: :delete, class: 'btn btn-sm btn-danger'

app/views/users/index.html.haml
%table.table.table-striped
  %thead
    %tr
      %th Email
  %tbody
    = render @users

= link_to 'Add user', new_user_path, class: 'btn btn-primary'

app/views/users/new.html.haml
= form_for @user do |f|
  = f.label :email
  = f.text_field :email
  = f.label :password
  = f.password_field :password
  = f.label :password_confirmation
  = f.password_field :password_confirmation
  = f.submit 'Create', class: 'btn btn-large btn-primary'

app/views/users_sessions/new.html.haml
%h1 Sign in
.row
  .col-md-6.col-md-offset-3
    = form_for(:user, url: users_sessions_path, html: {id: 'session'}) do |f|
      .form-group
        = f.label :email
        = f.email_field :email, class: 'form-control'

      .form-group
        = f.label :password
        = f.password_field :password, class: 'form-control'

      = f.submit 'Sign in', class: 'btn btn-large btn-primary'